[package]
name = "price"
version = "0.1.0"
edition = "2024"

[lib]
name = "price"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
tool_interface = { path = "../../libs/tool_interface" }
async-trait = "0.1"
serde_json = "1.0"